### ISSUE TITLE
./run_ansible doesnt work

### ISSUE THREAD

**Issue by jmcalalang** [jmcalalang/Ansible_Meetups#2]
new alpine image doesnt have bash, which is fine, but instead of the ``./run_ansible`` command its going to be ``ash run_ansible``.

this ok @ArtiomL ?

**Comment by ArtiomL** [comment]
[Shebang](https://en.wikipedia.org/wiki/Shebang_(Unix)) changed to `#!/bin/sh`

What's the meaning of Stonehenge? 🗿

**Comment by jmcalalang** [comment]
You right, you right!

[![Stonehenge](https://www.londonforfree.net/trips/stonehenge/)](https://www.youtube.com/watch?v=qAXzzHM8zLw "Stonehenge")
